name: Packer build qemu

on:
  push:
    tags:
      - '*'

permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Generate cloud-init iso
        run: |
           truncate -s 10G gentoo_root.img
           ls -alh
           tar --use-compress-program="gzip -0" -cvf gentoo_root.tar.gz gentoo_root.img
           split -b 1024mbb gentoo_root.tar.gz gentoo_root.tar.gz.part_
           ls -alh

      - name: upload
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "*.tar.gz.part_*"
          tags: true


          
          
