name: Packer build qemu

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Generate cloud-init iso
        run: |
           truncate -s 10G gentoo_root.img
           ls -alh
           zip -0 -s 2G -r gentoo_root.zip gentoo_root.img
           ls -alh

           

      

      # - name: copy file to s3 storage
      #   run: |
      #     aws s3 cp images/${{ github.event.workflow_run.head_branch }}.qcow2 s3://${{ secrets.S3_BUCKET }}/${{ github.event.workflow_run.head_branch }}.qcow2
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
      #     AWS_DEFAULT_REGION: ${{ secrets.S3_BUCKET_REGION }}
          
          
