name: Packer build qemu

on:
  push:
    tags:
      - '*'

permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Generate cloud-init iso
        run: |
           truncate -s 10G gentoo_root.img
           ls -alh
           zip -0 -s 100m -r zip_part_gentoo_root.zip gentoo_root.img
           ls -alh

      - name: upload
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "*.z*"
          tags: true


          
          
