name: Packer build qemu

on:
  push:
    tags:
      - '*'

permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Generate cloud-init iso
        run: |
           truncate -s 3G gentoo_root.img
           ls -alh
           tar -cvf gentoo_root.tar gentoo_root.img
           split -b 1024mb gentoo_root.tar gentoo_root.tar.part_
           ls -alh

      - name: upload
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "*.tar.part_*"
          tags: true


          
          
